name: Test installation control YAML

jobs:
  agama:
    container:
      image: registry.opensuse.org/yast/head/containers/containers_tumbleweed/opensuse/agama-web
      volumes:
        - dbus_run:/var/run/dbus
      env:
        TEST: test_env
    services:
      backend:
        image: registry.opensuse.org/yast/head/containers/containers_tumbleweed/opensuse/agama-service
        volumes:
          - dbus_run:/var/run/dbus
        env:
          SERVICE: test_service_env
  busybox:
    container:
      image: registry.opensuse.org/opensuse/busybox:latest
    needs:
      - agama
    steps:
      - run: /bin/bash
env:
  GLOBAL: test_global_env
