name: D-Installer workflow

jobs:
  dinstaller:
    container:
      image: registry.opensuse.org/yast/head/containers/containers_tumbleweed/opensuse/dinstaller-web
      volumes:
        - dbus_run:/run/d-installer
        - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    services:
      backend:
        image: registry.opensuse.org/yast/head/containers/containers_tumbleweed/opensuse/dinstaller-backend
        volumes:
          - dbus_run:/run/d-installer
          - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
          - /etc/NetworkManager:/etc/NetworkManager
